#!/usr/bin/env python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

import os.path
import platform
import sys

# Ensure we are running Python 2.7. We put this check here so we generate a
# user-friendly error message rather than a cryptic stack track on module
# import, etc.
major, minor, patchlevel = platform.python_version_tuple()

if major != '2' or minor != '7':
    print 'Python 2.7 is required to run mach. You are running %s.' % (
        platform.python_version() )
    sys.exit(1)

# Ideally we could load build/virtualenv/packages.txt. But, we need a
# supet set of what's in there, so we go with a one-off for now.
SEARCH_PATHS = [
    'python/mach',
    'python/mozbuild-bs',
    'build',
    'python/pymake-bs',
    'python/blessings',
    'other-licenses/ply',
    'xpcom/idl-parser',
    'testing/xpcshell',
    'testing/mozbase/mozprocess',
    'testing/mozbase/mozinfo',
]

our_dir = os.path.dirname(os.path.abspath(__file__))

try:
    import mach.main
except ImportError:
    SEARCH_PATHS.reverse()
    for path in SEARCH_PATHS:
        sys.path.insert(0, os.path.join(our_dir, path))

    import mach.main

# All of the code is in a module because EVERYTHING IS A LIBRARY.
mach = mach.main.Mach(our_dir)
mach.run(sys.argv[1:])
